version: "1.0"

services:
  mixing-valve-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: mixing-valve-frontend-image
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/usr/src/app/frontend
