version: "3.9"

services:
  frontend:
    container_name: mixing-valve-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}
    restart: always
    networks:
      - default

  backend:
    container_name: mixing-valve-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_PORT=${DB_PORT}
      - SESSION_KEY=${SESSION_KEY}
    restart: always
    networks:
      - default

