version: "3.9"

services:
  frontend:
    container_name: mixing-valve-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - .env
    restart: always
    networks:
      - default

  backend:
    container_name: mixing-valve-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:5000
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    restart: always
    networks:
      - default

